### ISSUE TITLE
lol the old links were really in the original torrent?

### ISSUE THREAD

**Issue by G2G2G2G** [shawwn/llama-dl#13]
from your readme:
>I doubt it. This is using the download link that was leaked in the original torrent. (i.e. the leaker accidentally leaked their own unique download link that Facebook sent them.)

The original guy verified his hashes with some other guy to make sure they weren't unique and then leaked it https://boards.4channel.org/g/thread/91848262#p91850335

I'm dying of laughter if he really did leak his URL in the torrent he posted after all that precaution lmao

**Comment by ValZapod** [comment]
>I'm dying of laughter if he really did leak his URL in the torrent he posted after all that precaution lmao

It was not his. He hacked some other entity.

**Comment by RokeJulianLockhart** [comment]
Did 4chan remove the thread?

**Comment by G2G2G2G** [comment]
there's no archive on 4chan all threads get removed.
 you can open it on a site that archives though like https://desuarchive.org/g/thread/91848262/#91850335

anyway I disagree he "hacked" anyone, it was probably him or his company.
