### ISSUE TITLE
The download address in the sh file is blocked.

### ISSUE THREAD

**Issue by Laser-Cho** [shawwn/llama-dl#23]
it shows "403 Forbidden".

Probably Facebook blocked it.

**Comment by nickdnickd** [comment]
Seeing this as well, trying the one from the comment right?

**Comment by Coderx7** [comment]
which link is dead for you? 
I got a checksum mismatch for the third part of 30B model (consolidated.03.pth: FAILED)

edit:
never mind, that was caused due to network failure on my part, re-downloading seems to be going without a hitch so far.

**Comment by Laser-Cho** [comment]
maybe I was wrong. I appologize it.
