### ISSUE TITLE
How to use these models?

### ISSUE THREAD

**Issue by berk-efe** [shawwn/llama-dl#8]
I dont have any idea how to use these model how can i learn it??
Also my computer have;
16gb ram
Geforce GT 640M GPU
i7-3630 CPU 2.40GHz

will i have a problem by creating photos with this AI?

**Comment by lucolivi** [comment]
You wont be able to run it locally with your configuration. Also this is a language model, it will output text, not images.

**Comment by berk-efe** [comment]
how can i do it ? @lucolivi 
I wanna learn more about it do you know how i cant,
so i wont bother u anymore...

**Comment by lucolivi** [comment]
Do what? Generate images? Try google colab + huggingface text2image models

**Comment by berk-efe** [comment]
oh thx!
but more spesificly i want to learn how do they do AI draw?

**Comment by lucolivi** [comment]
I think youtube is flooded with videos explaning how do these AI works. Check about diffusion models and GANs
