### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by amosayomide05** [shawwn/llama-dl#9]
After downloading this, how can I use it

Like how can I ask it a question

I am a noob 🫠

**Comment by Kyori-kyo** [comment]
I think...
you're downloading a machine learning file
so, to use it
you should download an app like PyTorch

**Comment by amosayomide05** [comment]
How 🥺🫣

**Comment by capripio** [comment]
@amosayomide05 , there is documentation available at official github page: https://github.com/facebookresearch/llama

**Comment by amosayomide05** [comment]
> @amosayomide05 , there is documentation available at official github page: https://github.com/facebookresearch/llama

The doc isn't for beginners

**Comment by mike-park** [comment]
Helpful instructions:

https://til.simonwillison.net/llms/llama-7b-m2

**Comment by Sandy4321** [comment]
cau I use it on windows 11?
